apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: alpine:latest
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /uploads
      name: uploads-volume
  volumes:
  - name: uploads-volume
    persistentVolumeClaim:
      claimName: uploads-pvc