apiVersion: batch/v1
kind: Job
metadata:
  name: wasm-test
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      containers:
      - image: wasmedge/example-wasi:latest
        name: wasm-test
        command: ["-h"]
      restartPolicy: Never
      runtimeClassName: wasmedge
  backoffLimit: 1