apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: filenames-test-wasm
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
      creationTimestamp: null
    spec:
      containers:
      - image: wapogal/scratch:latest
        imagePullPolicy: IfNotPresent
        name: filenames-test-wasm
        command: ["/app/main.wasm"]
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        hostPath:
          path: /mnt/host-folder/example-workload-dir
          type: Directory
      restartPolicy: Never
      runtimeClassName: wasmedge
  backoffLimit: 1