apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wasmrunners.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workloadId:
                  type: string
                proxyAddress:
                  type: string
                deleteAfterCompletion:
                  type: boolean
                  default: true
  scope: Namespaced
  names:
    plural: wasmrunners
    singular: wasmrunner
    kind: WasmRunner
    shortNames:
      - wr