apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wasmrunners.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workloadId:
                  type: string
                proxyAddress:
                  type: string
                deleteAfterCompletion:
                  type: boolean
                  default: true
                settings:
                  type: string
                  default: '{ "resource": "sample-data", "timeout": 60, "request": { "timeout": 1000, "max_bytes": 1000000 } }'
                resourceLimits:
                  type: string
                  default: '{ "cpu": "0.5", "memory": "512Mi" }'
                runtimeConfig:
                  type: string
                  default: '{ "runtimeClass": "wasmedge" }'
            status:
              type: object
              properties:
                phase:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: wasmrunners
    singular: wasmrunner
    kind: WasmRunner
    shortNames:
      - wr