[package]
name = "selector"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json"] }
tokio = { version = "1", features = ["rt", "macros", "net", "time"] }
serde_json = "1.0"