apiVersion: v1
kind: PersistentVolume
metadata:
  name: wasm-input-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/arthurpauwels/Documents/Masterproef/mp-k8s/wasm-follders/input"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wasm-input-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wasm-output-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/arthurpauwels/Documents/Masterproef/mp-k8s/wasm-follders/output"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wasm-output-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi