apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-folder-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/host-folder"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-folder-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual