apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-uploader
  template:
    metadata:
      labels:
        app: file-uploader
    spec:
      containers:
        - name: file-uploader
          image: wapogal/file-uploader:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          volumeMounts:
            - name: host-folder
              mountPath: /host-folder
      volumes:
        - name: host-folder
          hostPath:
            path: /mnt/host-folder