apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-uploader
  template:
    metadata:
      labels:
        app: file-uploader
    spec:
      containers:
        - name: file-uploader
          image: wapogal/file-uploader:latest
          env:
            - name: PROXY_ADDRESS
              value: redpanda.redpanda.svc.cluster.local:8083
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          volumeMounts:
            - name: workload-resources
              mountPath: /workload-resources
      volumes:
        - name: workload-resources
          persistentVolumeClaim:
            claimName: file-uploader-pvc