apiVersion: v1
kind: Service
metadata:
  name: file-uploader-service
spec:
  selector:
    app: file-uploader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
      nodePort: 30080
  type: NodePort