apiVersion: v1
kind: Service
metadata:
  name: workload-receiver-service
spec:
  selector:
    app: workload-receiver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
      nodePort: 30080
  type: NodePort