apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wasmrunners.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                command:
                  type: array
                  items:
                    type: string
                hostPath:
                  type: string
                name:
                  type: string
  scope: Namespaced
  names:
    plural: wasmrunners
    singular: wasmrunner
    kind: WasmRunner
    shortNames:
      - wr